/* Guardian Motors Limited: copies hand-authored static files (not generated by
   generate.js/minify.js) into the dist/ build output.
   Run with: node scripts/copy-static.js (also runs as part of `npm run build`) */
const fs = require('fs');
const path = require('path');
const { ROOT, OUT_DIR } = require('./build.js');

const FILES = ['manifest.json', 'sw.js', 'offline.html', 'robots.txt', 'sitemap.xml'];
const DIRS = ['assets', 'icons'];

fs.mkdirSync(OUT_DIR, { recursive: true });

for (const file of FILES) {
  fs.copyFileSync(path.join(ROOT, file), path.join(OUT_DIR, file));
  console.log('copied', file);
}

for (const dir of DIRS) {
  fs.cpSync(path.join(ROOT, dir), path.join(OUT_DIR, dir), {
    recursive: true,
    filter: (src) => !src.includes(`${path.sep}assets${path.sep}img${path.sep}originals`),
  });
  console.log('copied', dir + '/');
}

console.log('\nDone.');
